version: '3.9'
services:
  classroom:
    container_name: classroom
    build: .
    entrypoint: wait-for classroom_database:5432 -t 40 -- sh -c "npm install && npx prisma migrate dev && npm run start:dev"
    restart: always
    volumes:
      - .:/home/node/app
    ports:
      - 8002:8002
    depends_on:
      - classroom_database
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - classroom_network

  classroom_database:
    container_name: classroom_database
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - classroom_network

networks:
  classroom_network:
    driver: bridge

volumes:
  postgres:
