version: '3.9'
services:
  purchase:
    container_name: purchase
    build: .
    entrypoint: wait-for purchase_database:5432 -t 40 -- sh -c "npm install && npx prisma migrate dev && npm run start:dev"
    restart: always
    volumes:
      - .:/home/node/app
    ports:
      - 8001:8001
    depends_on:
      - purchase_database
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - purchase_network

  purchase_database:
    container_name: purchase_database
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - purchase_network

networks:
  purchase_network:
    driver: bridge

volumes:
  postgres:
