version: '3.9'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:172.17.0.1

  kafka-topics-generator:
    container_name: kafka-topics-generator
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=purchase.purchase-created --if-not-exists --bootstrap-server=kafka:9092"

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - 9021:9021
    env_file:
      - .env
